[package]
name = "Server-Launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.41"
colored_text = "0.3.0"
rusqlite = {  version ="0.35.0" , features = ["bundled"] }
serde = "1.0.219"
ratatui = "0.26.0"
crossterm = "0.27.0"
rand = "0.9.1"
